# coding: utf-8

"""
    Offer_1_0_Appendix

        Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from aws_marketplace_catalog_shapes_offer_1_0_appendix.models.configurable_upfront_pricing_term_type import ConfigurableUpfrontPricingTermType
from aws_marketplace_catalog_shapes_offer_1_0_appendix.models.configurable_upfront_rate_card_item import ConfigurableUpfrontRateCardItem
from aws_marketplace_catalog_shapes_offer_1_0_appendix.models.currency_code import CurrencyCode
from typing import Optional, Set
from typing_extensions import Self

class ConfigurableUpfrontPricingTerm(BaseModel):
    """
    ConfigurableUpfrontPricingTerm
    """ # noqa: E501
    type: ConfigurableUpfrontPricingTermType = Field(alias="Type")
    currency_code: CurrencyCode = Field(alias="CurrencyCode")
    rate_cards: Optional[Annotated[List[ConfigurableUpfrontRateCardItem], Field(min_length=1, max_length=5)]] = Field(default=None, alias="RateCards")
    __properties: ClassVar[List[str]] = ["Type", "CurrencyCode", "RateCards"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigurableUpfrontPricingTerm from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rate_cards (list)
        _items = []
        if self.rate_cards:
            for _item_rate_cards in self.rate_cards:
                if _item_rate_cards:
                    _items.append(_item_rate_cards.to_dict())
            _dict['RateCards'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigurableUpfrontPricingTerm from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Type": obj.get("Type"),
            "CurrencyCode": obj.get("CurrencyCode"),
            "RateCards": [ConfigurableUpfrontRateCardItem.from_dict(_item) for _item in obj["RateCards"]] if obj.get("RateCards") is not None else None
        })
        return _obj


