# coding: utf-8

"""
    Offer_1_0_Appendix

        Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LegalDocumentVersion(str, Enum):
    """
    LegalDocumentVersion
    """

    """
    allowed enum values
    """
    ENUM_2019_MINUS_04_MINUS_24 = '2019-04-24'
    ENUM_2022_MINUS_07_MINUS_14 = '2022-07-14'
    ENUM_2019_MINUS_12_MINUS_12 = '2019-12-12'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LegalDocumentVersion from a JSON string"""
        return cls(json.loads(json_str))


