# coding: utf-8

"""
    Offer_1_0_Appendix

        Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel, field_validator
from pydantic import Field
from typing_extensions import Annotated
from aws_marketplace_catalog_shapes_offer_1_0_appendix.models.support_term_type import SupportTermType
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SupportTerm(BaseModel):
    """
    SupportTerm
    """ # noqa: E501
    type: SupportTermType = Field(alias="Type")
    refund_policy: Annotated[str, Field(min_length=1, strict=True, max_length=500)] = Field(alias="RefundPolicy")
    __properties: ClassVar[List[str]] = ["Type", "RefundPolicy"]

    @field_validator('refund_policy')
    def refund_policy_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[\u0000-\u007E\u00A9\u00AE\u2122\u00A2-\u00A5]+$", value):
            raise ValueError(r"must validate the regular expression /^[\u0000-\u007E\u00A9\u00AE\u2122\u00A2-\u00A5]+$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SupportTerm from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SupportTerm from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Type": obj.get("Type"),
            "RefundPolicy": obj.get("RefundPolicy")
        })
        return _obj


