# coding: utf-8

"""
    ContainerProduct_1_0_ChangeTypes

        Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from pydantic import Field
from aws_marketplace_catalog_shapes_containerproduct_1_0_changetypes.models.add_delivery_options_ecr_delivery_option_details import AddDeliveryOptionsEcrDeliveryOptionDetails
from aws_marketplace_catalog_shapes_containerproduct_1_0_changetypes.models.add_delivery_options_eks_add_on_delivery_option_details import AddDeliveryOptionsEksAddOnDeliveryOptionDetails
from aws_marketplace_catalog_shapes_containerproduct_1_0_changetypes.models.add_delivery_options_helm_delivery_option_details import AddDeliveryOptionsHelmDeliveryOptionDetails
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AddDeliveryOptionDetails(BaseModel):
    """
    AddDeliveryOptionDetails
    """ # noqa: E501
    ecr_delivery_option_details: Optional[AddDeliveryOptionsEcrDeliveryOptionDetails] = Field(default=None, alias="EcrDeliveryOptionDetails")
    helm_delivery_option_details: Optional[AddDeliveryOptionsHelmDeliveryOptionDetails] = Field(default=None, alias="HelmDeliveryOptionDetails")
    eks_add_on_delivery_option_details: Optional[AddDeliveryOptionsEksAddOnDeliveryOptionDetails] = Field(default=None, alias="EksAddOnDeliveryOptionDetails")
    __properties: ClassVar[List[str]] = ["EcrDeliveryOptionDetails", "HelmDeliveryOptionDetails", "EksAddOnDeliveryOptionDetails"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AddDeliveryOptionDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ecr_delivery_option_details
        if self.ecr_delivery_option_details:
            _dict['EcrDeliveryOptionDetails'] = self.ecr_delivery_option_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of helm_delivery_option_details
        if self.helm_delivery_option_details:
            _dict['HelmDeliveryOptionDetails'] = self.helm_delivery_option_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of eks_add_on_delivery_option_details
        if self.eks_add_on_delivery_option_details:
            _dict['EksAddOnDeliveryOptionDetails'] = self.eks_add_on_delivery_option_details.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AddDeliveryOptionDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "EcrDeliveryOptionDetails": AddDeliveryOptionsEcrDeliveryOptionDetails.from_dict(obj.get("EcrDeliveryOptionDetails")) if obj.get("EcrDeliveryOptionDetails") is not None else None,
            "HelmDeliveryOptionDetails": AddDeliveryOptionsHelmDeliveryOptionDetails.from_dict(obj.get("HelmDeliveryOptionDetails")) if obj.get("HelmDeliveryOptionDetails") is not None else None,
            "EksAddOnDeliveryOptionDetails": AddDeliveryOptionsEksAddOnDeliveryOptionDetails.from_dict(obj.get("EksAddOnDeliveryOptionDetails")) if obj.get("EksAddOnDeliveryOptionDetails") is not None else None
        })
        return _obj


