# coding: utf-8

"""
    ContainerProduct_1_0_ChangeTypes

        Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, field_validator
from pydantic import Field
from typing_extensions import Annotated
from aws_marketplace_catalog_shapes_containerproduct_1_0_changetypes.models.add_delivery_option_details import AddDeliveryOptionDetails
from aws_marketplace_catalog_shapes_containerproduct_1_0_changetypes.models.add_delivery_option_visibility import AddDeliveryOptionVisibility
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AddDeliveryOption(BaseModel):
    """
    AddDeliveryOption
    """ # noqa: E501
    delivery_option_title: Optional[Annotated[str, Field(strict=True, max_length=72)]] = Field(default=None, alias="DeliveryOptionTitle")
    release: Optional[StrictBool] = Field(default=None, alias="Release")
    visibility: Optional[AddDeliveryOptionVisibility] = Field(default=None, alias="Visibility")
    details: Optional[AddDeliveryOptionDetails] = Field(default=None, alias="Details")
    __properties: ClassVar[List[str]] = ["DeliveryOptionTitle", "Release", "Visibility", "Details"]

    @field_validator('delivery_option_title')
    def delivery_option_title_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\S+[\S\s]*", value):
            raise ValueError(r"must validate the regular expression /^\S+[\S\s]*/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AddDeliveryOption from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of details
        if self.details:
            _dict['Details'] = self.details.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AddDeliveryOption from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "DeliveryOptionTitle": obj.get("DeliveryOptionTitle"),
            "Release": obj.get("Release"),
            "Visibility": obj.get("Visibility"),
            "Details": AddDeliveryOptionDetails.from_dict(obj.get("Details")) if obj.get("Details") is not None else None
        })
        return _obj


