# coding: utf-8

"""
    ContainerProduct_1_0_ChangeTypes

        Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, field_validator
from pydantic import Field
from typing_extensions import Annotated
from aws_marketplace_catalog_shapes_containerproduct_1_0_changetypes.models.override_parameter import OverrideParameter
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AddDeliveryOptionsHelmDeliveryOptionDetails(BaseModel):
    """
    AddDeliveryOptionsHelmDeliveryOptionDetails
    """ # noqa: E501
    description: Annotated[str, Field(strict=True, max_length=1000)] = Field(alias="Description")
    usage_instructions: Annotated[str, Field(strict=True, max_length=4000)] = Field(alias="UsageInstructions")
    container_images: Annotated[List[Annotated[str, Field(strict=True, max_length=1000)]], Field(min_length=1, max_length=50)] = Field(alias="ContainerImages")
    compatible_services: Annotated[List[Annotated[str, Field(strict=True)]], Field(min_length=1, max_length=2)] = Field(alias="CompatibleServices")
    helm_chart_uri: Annotated[str, Field(strict=True, max_length=1000)] = Field(alias="HelmChartUri")
    quick_launch_enabled: Optional[StrictBool] = Field(default=None, alias="QuickLaunchEnabled")
    release_name: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="ReleaseName")
    namespace: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="Namespace")
    marketplace_service_account_name: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="MarketplaceServiceAccountName")
    override_parameters: Optional[Annotated[List[OverrideParameter], Field(min_length=0, max_length=15)]] = Field(default=None, alias="OverrideParameters")
    __properties: ClassVar[List[str]] = ["Description", "UsageInstructions", "ContainerImages", "CompatibleServices", "HelmChartUri", "QuickLaunchEnabled", "ReleaseName", "Namespace", "MarketplaceServiceAccountName", "OverrideParameters"]

    @field_validator('description')
    def description_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\S+[\S\s]*", value):
            raise ValueError(r"must validate the regular expression /^\S+[\S\s]*/")
        return value

    @field_validator('usage_instructions')
    def usage_instructions_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\S+[\S\s]*", value):
            raise ValueError(r"must validate the regular expression /^\S+[\S\s]*/")
        return value

    @field_validator('helm_chart_uri')
    def helm_chart_uri_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\d{12}\.dkr\.ecr\.[a-z0-9-]{4,24}\.amazonaws\.com\/\S+", value):
            raise ValueError(r"must validate the regular expression /^\d{12}\.dkr\.ecr\.[a-z0-9-]{4,24}\.amazonaws\.com\/\S+/")
        return value

    @field_validator('release_name')
    def release_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\S+[\S\s]*", value):
            raise ValueError(r"must validate the regular expression /^\S+[\S\s]*/")
        return value

    @field_validator('namespace')
    def namespace_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\S+[\S\s]*", value):
            raise ValueError(r"must validate the regular expression /^\S+[\S\s]*/")
        return value

    @field_validator('marketplace_service_account_name')
    def marketplace_service_account_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\S+[\S\s]*", value):
            raise ValueError(r"must validate the regular expression /^\S+[\S\s]*/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AddDeliveryOptionsHelmDeliveryOptionDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in override_parameters (list)
        _items = []
        if self.override_parameters:
            for _item in self.override_parameters:
                if _item:
                    _items.append(_item.to_dict())
            _dict['OverrideParameters'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AddDeliveryOptionsHelmDeliveryOptionDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Description": obj.get("Description"),
            "UsageInstructions": obj.get("UsageInstructions"),
            "ContainerImages": obj.get("ContainerImages"),
            "CompatibleServices": obj.get("CompatibleServices"),
            "HelmChartUri": obj.get("HelmChartUri"),
            "QuickLaunchEnabled": obj.get("QuickLaunchEnabled"),
            "ReleaseName": obj.get("ReleaseName"),
            "Namespace": obj.get("Namespace"),
            "MarketplaceServiceAccountName": obj.get("MarketplaceServiceAccountName"),
            "OverrideParameters": [OverrideParameter.from_dict(_item) for _item in obj.get("OverrideParameters")] if obj.get("OverrideParameters") is not None else None
        })
        return _obj


