# coding: utf-8

"""
    SaaSProduct_1_0_ChangeTypes

        Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from pydantic import Field
from typing_extensions import Annotated
from aws_marketplace_catalog_shapes_saasproduct_1_0_changetypes.models.cloud_formation_details import CloudFormationDetails
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DeploymentTemplate(BaseModel):
    """
    DeploymentTemplate
    """ # noqa: E501
    title: Annotated[str, Field(strict=True, max_length=128)] = Field(alias="Title")
    description: Optional[Annotated[str, Field(strict=True, max_length=4000)]] = Field(default=None, alias="Description")
    iam_policy: Annotated[str, Field(strict=True, max_length=6144)] = Field(alias="IamPolicy")
    cloud_formation_details: CloudFormationDetails = Field(alias="CloudFormationDetails")
    __properties: ClassVar[List[str]] = ["Title", "Description", "IamPolicy", "CloudFormationDetails"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DeploymentTemplate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cloud_formation_details
        if self.cloud_formation_details:
            _dict['CloudFormationDetails'] = self.cloud_formation_details.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DeploymentTemplate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Title": obj.get("Title"),
            "Description": obj.get("Description"),
            "IamPolicy": obj.get("IamPolicy"),
            "CloudFormationDetails": CloudFormationDetails.from_dict(obj.get("CloudFormationDetails")) if obj.get("CloudFormationDetails") is not None else None
        })
        return _obj


