# coding: utf-8

"""
    SaaSProduct_1_0_ChangeTypes

        Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, field_validator
from pydantic import Field
from typing_extensions import Annotated
from aws_marketplace_catalog_shapes_saasproduct_1_0_changetypes.models.deployment_template import DeploymentTemplate
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UpdateSaaSUrlDeliveryOptionDetails(BaseModel):
    """
    One of [FulfillmentUrl, LaunchUrl, DeploymentTemplates, UsageInstructions] is required
    """ # noqa: E501
    fulfillment_url: Optional[Annotated[str, Field(min_length=8, strict=True, max_length=2048)]] = Field(default=None, alias="FulfillmentUrl")
    launch_url: Optional[Annotated[str, Field(min_length=8, strict=True, max_length=2048)]] = Field(default=None, alias="LaunchUrl")
    deployment_templates: Optional[Annotated[List[DeploymentTemplate], Field(min_length=1, max_length=20)]] = Field(default=None, alias="DeploymentTemplates")
    usage_instructions: Optional[Annotated[str, Field(strict=True, max_length=30000)]] = Field(default=None, alias="UsageInstructions")
    __properties: ClassVar[List[str]] = ["FulfillmentUrl", "LaunchUrl", "DeploymentTemplates", "UsageInstructions"]

    @field_validator('fulfillment_url')
    def fulfillment_url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"https:\/\/(www\.)?[-a-zA-Z0-9@._]{1,256}\.[a-zA-Z0-9()]{1,63}\b([-a-zA-Z0-9@_\+.\/\/]*)", value):
            raise ValueError(r"must validate the regular expression /https:\/\/(www\.)?[-a-zA-Z0-9@._]{1,256}\.[a-zA-Z0-9()]{1,63}\b([-a-zA-Z0-9@_\+.\/\/]*)/")
        return value

    @field_validator('launch_url')
    def launch_url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"https:\/\/(www\.)?[-a-zA-Z0-9@._]{1,256}\.[a-zA-Z0-9()]{1,63}\b([-a-zA-Z0-9@_\+.\/\/]*)", value):
            raise ValueError(r"must validate the regular expression /https:\/\/(www\.)?[-a-zA-Z0-9@._]{1,256}\.[a-zA-Z0-9()]{1,63}\b([-a-zA-Z0-9@_\+.\/\/]*)/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UpdateSaaSUrlDeliveryOptionDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in deployment_templates (list)
        _items = []
        if self.deployment_templates:
            for _item in self.deployment_templates:
                if _item:
                    _items.append(_item.to_dict())
            _dict['DeploymentTemplates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UpdateSaaSUrlDeliveryOptionDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "FulfillmentUrl": obj.get("FulfillmentUrl"),
            "LaunchUrl": obj.get("LaunchUrl"),
            "DeploymentTemplates": [DeploymentTemplate.from_dict(_item) for _item in obj.get("DeploymentTemplates")] if obj.get("DeploymentTemplates") is not None else None,
            "UsageInstructions": obj.get("UsageInstructions")
        })
        return _obj


