# coding: utf-8

"""
    ResaleAuthorization_1_0_EntityType

        Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from pydantic import Field
from aws_marketplace_catalog_shapes_resaleauthorization_1_0_entitytype.models.constraints import Constraints
from aws_marketplace_catalog_shapes_resaleauthorization_1_0_entitytype.models.rate_card import RateCard
from aws_marketplace_catalog_shapes_resaleauthorization_1_0_entitytype.models.selector import Selector
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RateCards(BaseModel):
    """
    RateCards
    """ # noqa: E501
    selector: Optional[Selector] = Field(default=None, alias="Selector")
    rate_card: Optional[List[RateCard]] = Field(default=None, alias="RateCard")
    constraints: Optional[Constraints] = Field(default=None, alias="Constraints")
    __properties: ClassVar[List[str]] = ["Selector", "RateCard", "Constraints"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RateCards from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of selector
        if self.selector:
            _dict['Selector'] = self.selector.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in rate_card (list)
        _items = []
        if self.rate_card:
            for _item in self.rate_card:
                if _item:
                    _items.append(_item.to_dict())
            _dict['RateCard'] = _items
        # override the default output from pydantic by calling `to_dict()` of constraints
        if self.constraints:
            _dict['Constraints'] = self.constraints.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RateCards from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Selector": Selector.from_dict(obj.get("Selector")) if obj.get("Selector") is not None else None,
            "RateCard": [RateCard.from_dict(_item) for _item in obj.get("RateCard")] if obj.get("RateCard") is not None else None,
            "Constraints": Constraints.from_dict(obj.get("Constraints")) if obj.get("Constraints") is not None else None
        })
        return _obj


