# coding: utf-8

"""
    Offer_1_0

        Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from aws_marketplace_catalog_shapes_offer_1_0.models.constraints import Constraints
from aws_marketplace_catalog_shapes_offer_1_0.models.rate_card_item import RateCardItem
from aws_marketplace_catalog_shapes_offer_1_0.models.selector import Selector
from typing import Optional, Set
from typing_extensions import Self

class RateCardsItem(BaseModel):
    """
    RateCardsItem
    """ # noqa: E501
    selector: Optional[Selector] = Field(default=None, alias="Selector")
    constraints: Optional[Constraints] = Field(default=None, alias="Constraints")
    rate_card: Optional[List[RateCardItem]] = Field(default=None, alias="RateCard")
    __properties: ClassVar[List[str]] = ["Selector", "Constraints", "RateCard"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RateCardsItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of selector
        if self.selector:
            _dict['Selector'] = self.selector.to_dict()
        # override the default output from pydantic by calling `to_dict()` of constraints
        if self.constraints:
            _dict['Constraints'] = self.constraints.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in rate_card (list)
        _items = []
        if self.rate_card:
            for _item_rate_card in self.rate_card:
                if _item_rate_card:
                    _items.append(_item_rate_card.to_dict())
            _dict['RateCard'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RateCardsItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Selector": Selector.from_dict(obj["Selector"]) if obj.get("Selector") is not None else None,
            "Constraints": Constraints.from_dict(obj["Constraints"]) if obj.get("Constraints") is not None else None,
            "RateCard": [RateCardItem.from_dict(_item) for _item in obj["RateCard"]] if obj.get("RateCard") is not None else None
        })
        return _obj


