# coding: utf-8

"""
    AmiProduct_1_0_EntityType

        Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from aws_marketplace_catalog_shapes_amiproduct_1_0_entitytype.models.additional_resource import AdditionalResource
from aws_marketplace_catalog_shapes_amiproduct_1_0_entitytype.models.promotional_media import PromotionalMedia
from aws_marketplace_catalog_shapes_amiproduct_1_0_entitytype.models.video import Video
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PromotionalResources(BaseModel):
    """
    PromotionalResources
    """ # noqa: E501
    logo_url: Optional[StrictStr] = Field(default=None, alias="LogoUrl")
    videos: Optional[List[Video]] = Field(default=None, alias="Videos")
    additional_resources: Optional[List[AdditionalResource]] = Field(default=None, alias="AdditionalResources")
    promotional_media: Optional[List[PromotionalMedia]] = Field(default=None, alias="PromotionalMedia")
    __properties: ClassVar[List[str]] = ["LogoUrl", "Videos", "AdditionalResources", "PromotionalMedia"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PromotionalResources from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in videos (list)
        _items = []
        if self.videos:
            for _item in self.videos:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Videos'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in additional_resources (list)
        _items = []
        if self.additional_resources:
            for _item in self.additional_resources:
                if _item:
                    _items.append(_item.to_dict())
            _dict['AdditionalResources'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in promotional_media (list)
        _items = []
        if self.promotional_media:
            for _item in self.promotional_media:
                if _item:
                    _items.append(_item.to_dict())
            _dict['PromotionalMedia'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PromotionalResources from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "LogoUrl": obj.get("LogoUrl"),
            "Videos": [Video.from_dict(_item) for _item in obj.get("Videos")] if obj.get("Videos") is not None else None,
            "AdditionalResources": [AdditionalResource.from_dict(_item) for _item in obj.get("AdditionalResources")] if obj.get("AdditionalResources") is not None else None,
            "PromotionalMedia": [PromotionalMedia.from_dict(_item) for _item in obj.get("PromotionalMedia")] if obj.get("PromotionalMedia") is not None else None
        })
        return _obj


