# coding: utf-8

"""
    MachineLearningProduct_1_0_ChangeTypes

        Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from aws_marketplace_catalog_shapes_machinelearningproduct_1_0_changetypes.models.parameter import Parameter
from aws_marketplace_catalog_shapes_machinelearningproduct_1_0_changetypes.models.sample import Sample
from typing import Optional, Set
from typing_extensions import Self

class InputProperties(BaseModel):
    """
    InputProperties
    """ # noqa: E501
    description: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=10000)]] = Field(default=None, alias="Description")
    limitations: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=1000)]] = Field(default=None, alias="Limitations")
    sample_input: Optional[Sample] = Field(default=None, alias="SampleInput")
    parameters: Optional[Annotated[List[Parameter], Field(min_length=0, max_length=35)]] = Field(default=None, alias="Parameters")
    sage_maker_custom_attributes: Optional[Annotated[List[Parameter], Field(min_length=0, max_length=35)]] = Field(default=None, alias="SageMakerCustomAttributes")
    __properties: ClassVar[List[str]] = ["Description", "Limitations", "SampleInput", "Parameters", "SageMakerCustomAttributes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InputProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sample_input
        if self.sample_input:
            _dict['SampleInput'] = self.sample_input.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in parameters (list)
        _items = []
        if self.parameters:
            for _item_parameters in self.parameters:
                if _item_parameters:
                    _items.append(_item_parameters.to_dict())
            _dict['Parameters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sage_maker_custom_attributes (list)
        _items = []
        if self.sage_maker_custom_attributes:
            for _item_sage_maker_custom_attributes in self.sage_maker_custom_attributes:
                if _item_sage_maker_custom_attributes:
                    _items.append(_item_sage_maker_custom_attributes.to_dict())
            _dict['SageMakerCustomAttributes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InputProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Description": obj.get("Description"),
            "Limitations": obj.get("Limitations"),
            "SampleInput": Sample.from_dict(obj["SampleInput"]) if obj.get("SampleInput") is not None else None,
            "Parameters": [Parameter.from_dict(_item) for _item in obj["Parameters"]] if obj.get("Parameters") is not None else None,
            "SageMakerCustomAttributes": [Parameter.from_dict(_item) for _item in obj["SageMakerCustomAttributes"]] if obj.get("SageMakerCustomAttributes") is not None else None
        })
        return _obj


