# coding: utf-8

"""
    MachineLearningProduct_1_0_ChangeTypes

        Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved. 

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from aws_marketplace_catalog_shapes_machinelearningproduct_1_0_changetypes.models.input_properties import InputProperties
from aws_marketplace_catalog_shapes_machinelearningproduct_1_0_changetypes.models.output_properties import OutputProperties
from aws_marketplace_catalog_shapes_machinelearningproduct_1_0_changetypes.models.sage_maker_algorithm_recommended_instance_types import SageMakerAlgorithmRecommendedInstanceTypes
from typing import Optional, Set
from typing_extensions import Self

class UpdateDeliveryOptionsSageMakerAlgorithmDeliveryOptionDetails(BaseModel):
    """
    UpdateDeliveryOptionsSageMakerAlgorithmDeliveryOptionDetails
    """ # noqa: E501
    usage_instructions: Optional[Annotated[str, Field(strict=True, max_length=10000)]] = Field(default=None, alias="UsageInstructions")
    sample_notebook_url: Optional[Annotated[str, Field(strict=True, max_length=2000)]] = Field(default=None, alias="SampleNotebookUrl")
    repository_url: Optional[Annotated[str, Field(strict=True, max_length=2000)]] = Field(default=None, alias="RepositoryUrl")
    input_properties: Optional[InputProperties] = Field(default=None, alias="InputProperties")
    output_properties: Optional[OutputProperties] = Field(default=None, alias="OutputProperties")
    recommended_instance_types: Optional[SageMakerAlgorithmRecommendedInstanceTypes] = Field(default=None, alias="RecommendedInstanceTypes")
    __properties: ClassVar[List[str]] = ["UsageInstructions", "SampleNotebookUrl", "RepositoryUrl", "InputProperties", "OutputProperties", "RecommendedInstanceTypes"]

    @field_validator('sample_notebook_url')
    def sample_notebook_url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^https:\/\/(www\.)?[-a-zA-Z0-9@._]{1,256}\.[a-zA-Z0-9()]{2,63}\b([-a-zA-Z0-9@_+.\/]*)", value):
            raise ValueError(r"must validate the regular expression /^https:\/\/(www\.)?[-a-zA-Z0-9@._]{1,256}\.[a-zA-Z0-9()]{2,63}\b([-a-zA-Z0-9@_+.\/]*)/")
        return value

    @field_validator('repository_url')
    def repository_url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^https:\/\/(www\.)?[-a-zA-Z0-9@._]{1,256}\.[a-zA-Z0-9()]{2,63}\b([-a-zA-Z0-9@_+.\/]*)", value):
            raise ValueError(r"must validate the regular expression /^https:\/\/(www\.)?[-a-zA-Z0-9@._]{1,256}\.[a-zA-Z0-9()]{2,63}\b([-a-zA-Z0-9@_+.\/]*)/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateDeliveryOptionsSageMakerAlgorithmDeliveryOptionDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input_properties
        if self.input_properties:
            _dict['InputProperties'] = self.input_properties.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output_properties
        if self.output_properties:
            _dict['OutputProperties'] = self.output_properties.to_dict()
        # override the default output from pydantic by calling `to_dict()` of recommended_instance_types
        if self.recommended_instance_types:
            _dict['RecommendedInstanceTypes'] = self.recommended_instance_types.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateDeliveryOptionsSageMakerAlgorithmDeliveryOptionDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "UsageInstructions": obj.get("UsageInstructions"),
            "SampleNotebookUrl": obj.get("SampleNotebookUrl"),
            "RepositoryUrl": obj.get("RepositoryUrl"),
            "InputProperties": InputProperties.from_dict(obj["InputProperties"]) if obj.get("InputProperties") is not None else None,
            "OutputProperties": OutputProperties.from_dict(obj["OutputProperties"]) if obj.get("OutputProperties") is not None else None,
            "RecommendedInstanceTypes": SageMakerAlgorithmRecommendedInstanceTypes.from_dict(obj["RecommendedInstanceTypes"]) if obj.get("RecommendedInstanceTypes") is not None else None
        })
        return _obj


